name: Publish Release APK

on: workflow_dispatch

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'keystore/release.keystore'
        encodedString: ${{ secrets.KEYSTORE }}
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        path: app/build/outputs/*.apk
    - name: Releasing using Hub
      uses: r0user/release-apk@main
      env:
       GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
       APP_FOLDER: app
    - name: r0adkll
      uses: r0adkll/sign-android-release@v1
    - name: Sign app APK
    # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
