## 1
name: Test and deploy

on: workflow_dispatch

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew
      
      - name: Unit tests
        run: ./gradlew test
  ## 4
  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
