name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dishapatel010/android-public-build@main
        with:
            token: ${{ secrets.GITUB_TOKEN }}
