name: Notify on Telegram

on:
  fork:
  push:
  release:
    types: [published, unpublished, created, edited, deleted, prereleased, released]
  issue_comment:
    types: [created, edited, deleted]
  watch:
    types: started
  pull_request_review_comment:
    types: created
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, pinned, closed, reopened]
  label:
    types: [created, edited, deleted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Github Telegram Notifier - Topics
        uses: dishapatel010/github-telegram-notify@V1.1.3
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
          thread_id: '${{ secrets.THREAD_ID }}'
